name: fittingAlgorithms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - c-compiler
  - cxx-compiler
  - cmake
  - make
  - eigen
  - boost
  - doxygen
  - pip:
    - breathe==4.35.0
    - sphinx==7.4.7
    - sphinx_rtd_theme==2.0.0
